function ReturnMO() { 
    return(
<select class="form-control" size='sm'>
    <option>Select the microorganism</option>
    <option value="1">Acetobacter aurantius</option>
    <option value="2">Acinetobacter baumannii</option>
    <option value="3">Actinomyces israelii</option>
    <option value="4">Agrobacterium radiobacter</option>
    <option value="5">Agrobacterium tumefaciens</option>
    <option value="6">Anaplasma</option>
    <option value="7">Anaplasma phagocytophilum</option>
    <option value="8">Azorhizobium caulinodans</option>
    <option value="9">Azotobacter vinelandii</option>
    <option value="10">Viridans streptococci</option>
    <option value="11">Bacillus</option>
    <option value="12">Bacillus anthracis</option>
    <option value="13">Bacillus brevis</option>
    <option value="14">Bacillus cereus</option>
    <option value="15">Bacillus fusiformis</option>
    <option value="16">Bacillus licheniformis</option>
    <option value="17">Bacillus megaterium</option>
    <option value="18">Bacillus mycoides</option>
    <option value="19">Bacillus stearothermophilus</option>
    <option value="20">Bacillus subtilis</option>
    <option value="21">Bacillus thuringiensis</option>
    <option value="22">Bacteroides</option>
    <option value="23">Bacteroides fragilis</option>
    <option value="24">Bacteroides gingivalis</option>
    <option value="25">Bacteroides melaninogenicus</option>
    <option value="26">Bartonella</option>
    <option value="27">Bartonella henselae</option>
    <option value="28">Bartonella quintana</option>
    <option value="29">Bordetella</option>
    <option value="30">Bordetella bronchiseptica</option>
    <option value="31">Bordetella pertussis</option>
    <option value="32">Borrelia burgdorferi</option>
    <option value="33">Brucella</option>
    <option value="34">Brucella abortus</option>
    <option value="35">Brucella melitensis</option>
    <option value="36">Brucella suis</option>
    <option value="37">Burkholderia</option>
    <option value="38">Burkholderia mallei</option>
    <option value="39">Burkholderia pseudomallei</option>
    <option value="40">Burkholderia cepacia</option>
    <option value="41">Calymmatobacterium granulomatis</option>
    <option value="42">Campylobacter</option>
    <option value="43">Campylobacter coli</option>
    <option value="44">Campylobacter fetus</option>
    <option value="45">Campylobacter jejuni</option>
    <option value="46">Campylobacter pylori</option>
    <option value="47">Chlamydia</option>
    <option value="48">Chlamydia trachomatis</option>
    <option value="49">Chlamydophila</option>
    <option value="50">Chlamydophila pneumoniae</option>
    <option value="51">Chlamydophila psittaci</option>
    <option value="52">Clostridium</option>
    <option value="53">Clostridium botulinum</option>
    <option value="54">Clostridium difficile</option>
    <option value="55">Clostridium perfringens</option>
    <option value="56">Clostridium tetani</option>
    <option value="57">Corynebacterium</option>
    <option value="58">Corynebacterium diphtheriae</option>
    <option value="59">Corynebacterium fusiforme</option>
    <option value="60">Coxiella burnetii</option>
    <option value="61">Ehrlichia chaffeensis</option>
    <option value="62">Ehrlichia ewingii</option>
    <option value="63">Eikenella corrodens</option>
    <option value="64">Enterobacter cloacae</option>
    <option value="65">Enterococcus</option>
    <option value="66">Enterococcus avium</option>
    <option value="67">Enterococcus durans</option>
    <option value="68">Enterococcus faecalis</option>
    <option value="69">Enterococcus faecium</option>
    <option value="70">Enterococcus gallinarum</option>
    <option value="71">Enterococcus maloratus</option>
    <option value="72">Escherichia coli</option>
    <option value="73">Fusobacterium necrophorum</option>
    <option value="74">Fusobacterium nucleatum</option>
    <option value="75">Gardnerella vaginalis</option>
    <option value="76">Haemophilus</option>
    <option value="77">Haemophilus ducreyi</option>
    <option value="78">Haemophilus influenzae</option>
    <option value="79">Haemophilus parainfluenzae</option>
    <option value="80">Haemophilus pertussis</option>
    <option value="81">Haemophilus vaginalis</option>
    <option value="82">Helicobacter pylori</option>
    <option value="83">Klebsiella pneumoniae</option>
    <option value="84">Lactobacillus</option>
    <option value="85">Lactobacillus acidophilus</option>
    <option value="86">Lactobacillus bulgaricus</option>
    <option value="87">Lactobacillus casei</option>
    <option value="88">Lactococcus lactis</option>
    <option value="89">Legionella pneumophila</option>
    <option value="90">Leptospira interrogans</option>
    <option value="91">Leptospira noguchii</option>
    <option value="92">Listeria monocytogenes</option>
    <option value="93">Methanobacterium extroquens</option>
    <option value="94">Microbacterium multiforme</option>
    <option value="95">Micrococcus luteus</option>
    <option value="96">Moraxella catarrhalis</option>
    <option value="97">Mycobacterium</option>
    <option value="98">Mycobacterium avium</option>
    <option value="99">Mycobacterium bovis</option>
    <option value="100">Mycobacterium diphtheriae</option>
    <option value="101">Mycobacterium intracellulare</option>
    <option value="102">Mycobacterium leprae</option>
    <option value="103">Mycobacterium lepraemurium</option>
    <option value="104">Mycobacterium phlei</option>
    <option value="105">Mycobacterium smegmatis</option>
    <option value="106">Mycobacterium tuberculosis</option>
    <option value="107">Mycoplasma</option>
    <option value="108">Mycoplasma fermentans</option>
    <option value="109">Mycoplasma genitalium</option>
    <option value="110">Mycoplasma hominis</option>
    <option value="111">Mycoplasma penetrans</option>
    <option value="112">Mycoplasma pneumoniae</option>
    <option value="113">Mycoplasma mexican</option>
    <option value="114">Neisseria</option>
    <option value="115">Neisseria gonorrhoeae</option>
    <option value="116">Neisseria meningitidis</option>
    <option value="117">Pasteurella</option>
    <option value="118">Pasteurella multocida</option>
    <option value="119">Pasteurella tularensis</option>
    <option value="120">Peptostreptococcus</option>
    <option value="121">Porphyromonas gingivalis</option>
    <option value="122">Prevotella melaninogenica</option>
    <option value="123">Pseudomonas aeruginosa</option>
    <option value="124">Rhizobium radiobacter</option>
    <option value="125">Rickettsia</option>
    <option value="126">Rickettsia prowazekii</option>
    <option value="127">Rickettsia psittaci</option>
    <option value="128">Rickettsia quintana</option>
    <option value="129">Rickettsia rickettsii</option>
    <option value="130">Rickettsia trachomae</option>
    <option value="131">Rochalimaea</option>
    <option value="132">Rochalimaea henselae</option>
    <option value="133">Rochalimaea quintana</option>
    <option value="134">Rothia dentocariosa</option>
    <option value="135">Salmonella</option>
    <option value="136">Salmonella enteritidis</option>
    <option value="137">Salmonella typhi</option>
    <option value="138">Salmonella typhimurium</option>
    <option value="139">Serratia marcescens</option>
    <option value="140">Shigella dysenteriae</option>
    <option value="141">Spirillum volutans</option>
    <option value="142">Staphylococcus</option>
    <option value="143">Staphylococcus aureus</option>
    <option value="144">Staphylococcus epidermidis</option>
    <option value="145">Stenotrophomonas maltophilia</option>
    <option value="146">Streptococcus</option>
    <option value="147">Streptococcus agalactiae</option>
    <option value="148">Streptococcus avium</option>
    <option value="149">Streptococcus bovis</option>
    <option value="150">Streptococcus cricetus</option>
    <option value="151">Streptococcus faceium</option>
    <option value="152">Streptococcus faecalis</option>
    <option value="153">Streptococcus ferus</option>
    <option value="154">Streptococcus gallinarum</option>
    <option value="155">Streptococcus lactis</option>
    <option value="156">Streptococcus mitior</option>
    <option value="157">Streptococcus mitis</option>
    <option value="158">Streptococcus mutans</option>
    <option value="159">Streptococcus oralis</option>
    <option value="160">Streptococcus pneumoniae</option>
    <option value="161">Streptococcus pyogenes</option>
    <option value="162">Streptococcus rattus</option>
    <option value="163">Streptococcus salivarius</option>
    <option value="164">Streptococcus sanguis</option>
    <option value="165">Streptococcus sobrinus</option>
    <option value="166">Treponema</option>
    <option value="167">Ureaplasma urealyticum</option>
    <option value="168">Vibrio</option>
    <option value="169">Vibrio cholerae</option>
    <option value="170">Vibrio comma</option>
    <option value="171">Vibrio parahaemolyticus</option>
    <option value="172">Vibrio vulnificus</option>
    <option value="173">Wolbachia</option>
    <option value="174">Yersinia</option>
    <option value="175">Yersinia enterocolitica</option>
    <option value="176">Yersinia pestis</option>
    <option value="177">Yersinia pseudotuberculosis</option>
</select>
);
};

export default ReturnMO;